# Generated by Django 3.1.3 on 2021-05-29 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20210517_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookmarkProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_product', to='mainapp.product', verbose_name='Товар')),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_holder', to=settings.AUTH_USER_MODEL, verbose_name='Полкупатель')),
            ],
            options={
                'verbose_name': 'Избранные товары',
                'verbose_name_plural': 'Избранные товары',
                'ordering': ['product'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmark_creator', through='mainapp.BookmarkProduct', to=settings.AUTH_USER_MODEL, verbose_name='владелец закладки'),
        ),
    ]
