# Generated by Django 3.1.3 on 2021-06-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210529_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование бренда')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
